addCommandHandler("tuning",function(thePlayer,cmd)
    veh = getPedOccupiedVehicle ( thePlayer )
    addVehicleUpgrade ( getPedOccupiedVehicle ( thePlayer ),"all")
    removeVehicleUpgrade ( getPedOccupiedVehicle ( thePlayer ),1131)
    ped1 = createPed(102,0,0,0)
    ped2 = createPed(103,0,0,0)
    ped3 = createPed(104,0,0,0)
    warpPedIntoVehicle(ped1,veh,1)
    warpPedIntoVehicle(ped2,veh,2)
    warpPedIntoVehicle(ped3,veh,3)
end)
