core = exports.oCore

animations = {
	{'daps', 'GANGS', 'hndshkfa',-1, false},
	{'daps2', 'GANGS', 'hndshkca',-1, false},
	{'heil', 'ON_LOOKERS', 'Pointup_in',-1, false},
	{'salute', 'ON_LOOKERS', 'Pointup_in',-1, false},
    {'dance', 'DANCING', 'DAN_Right_A',-1, true},
	{'dance2', 'DANCING', 'DAN_Down_A',-1, true},
	{'dance3', 'DANCING', 'dnce_M_d',-1, true},
	{'dance4', 'DANCING', 'dance_loop', -1, true},
	{'dance5', 'DANCING', 'dan_left_a', -1, true},
	{'dance6', 'DANCING', 'dan_loop_a', -1, true},
	{'dance7', 'DANCING', 'dan_up_a', -1, true},
	{'dance8', 'DANCING', 'dnce_m_a', -1, true},
	{'dance9', 'DANCING', 'dnce_m_b', -1, true},
	{'dance10', 'DANCING', 'dnce_m_c', -1, true},
	{'strip', 'STRIP', 'strip_D',-1, true},
	{'strip2', 'STRIP', 'STR_Loop_C',-1, true},
	{"sit4", "BEACH", "ParkSit_W_loop", -1, true},
	{"sit5", "BEACH", "ParkSit_M_loop", -1, true},
	{'gsign', 'GHANDS', 'gsign1', -1, true},
	{'gsign2', 'GHANDS', 'gsign2', -1, true},
	{'gsign3', 'GHANDS', 'gsign3', -1, true},
	{'gsign4', 'GHANDS', 'gsign4', -1, true},
	{'gsign5', 'GHANDS', 'gsign5', -1, true},
	{'rap', 'LOWRIDER', 'RAP_A_Loop',-1, true},
	{'rap2', 'LOWRIDER', 'RAP_B_Loop',-1, true},
	{'rap3', 'LOWRIDER', 'RAP_C_Loop',-1, true},
	{'cheer', 'STRIP', 'PUN_HOLLER',-1, true},
	{'cheer2', 'OTB', 'wtchrace_win',-1, true},
	{'cheer3', 'RIOT', 'RIOT_shout',-1, true},
	{'fixcar', 'CAR', 'Fixn_Car_loop',-1, false},
	{'startrace', 'CAR', 'flag_drop',-1, false},
	{'carchat', 'CAR_CHAT', 'car_talkm_loop',-1, true},
	{'carphone', 'CAR_CHAT', 'carfone_loopA',-1, true},
	{'carphone2', 'CAR_CHAT', 'carfone_loopB',-1, true},
	{'fixing', 'BOMBER', 'BOM_Plant_Loop',-1, false}, 
	{"crack", "crack", "crckidle1", -1, true},
	{"crack2", "crack", "crckidle2", -1, true},
	{"crack3", "crack", "crckidle3", -1, true},
	{"crack4", "crack", "crckidle4", -1, true},
	{'leanleft', 'MISC', 'Plyrlean_loop', -1, true},
	{"copaway", "police", "coptraf_away", -1, true},
	{"copcome", "police", "CopTraf_Come", -1, true},
	{"copleft", "police", "CopTraf_Left", -1, true},
	{"copstop", "police", "CopTraf_Stop", -1, true},
	{'shake', 'COP_AMBIENT', 'Coplook_shake',-1, false},
	{'lean', 'GANGS', 'leanIDLE',-1, false},
	{'idle', 'DEALER', 'DEALER_IDLE_01',-1, false},
	{'piss', 'PAULNMAC', 'Piss_loop',-1, true},
	{'wank', 'PAULNMAC', 'wank_loop',-1, true},
	{"wait", "COP_AMBIENT", "Coplook_loop", -1, false},
	{'tired', 'FAT', 'idle_tired',-1, true},
	{'fallfront', 'ped', 'FLOOR_hit_f',-1, false},
	{'fall', 'ped', 'FLOOR_hit',-1, false},
	{"think", "COP_AMBIENT", "Coplook_think", -1, true},
	{'crouch', 'CAMERA', 'camstnd_to_camcrch',-1, false},
	{'shocked', 'ON_LOOKERS', 'panic_loop',-1, false},
	{'cover', 'ped', 'duck_cower',-1, true},
	{'smoke', 'GANGS', 'smkcig_prtl',-1, true},
	{'smoke2', 'SMOKING', 'M_smkstnd_loop',-1, true},
	{'smoke3', 'LOWRIDER', 'M_smkstnd_loop',-1, true},
	{'smokelean', 'LOWRIDER', 'M_smklean_loop',-1, true},
	{'lightup', 'SMOKING', 'M_smk_in',-1, false},
	{'drag', 'SMOKING', 'M_smk_drag',-1, false},
	{"sit", "ped", "SEAT_idle", -1, false},
	{"sit2", "FOOD", "FF_Sit_Look", -1, true},
	{"sit3", "Attractors", "Stepsit_loop", -1, true},
	{"sit4", "BEACH", "ParkSit_W_loop", -1, true},
	{"sit5", "BEACH", "ParkSit_M_loop", -1, true},
	{"lay", "BEACH", "Lay_Bac_Loop", -1, true},
	{"lay2", "BEACH", "sitnwait_Loop_W", -1, true},
	{"aim", "SHOP", "ROB_Loop_Threat", -1, true},
	{"aim2", "ped", "ARRESTgun", -1, false},
	{'hailtaxi', 'MISC', 'Hiker_Pose',-1, false},
	{'hailcab', 'MISC', 'Hiker_Pose',-1, false},
	{'crouch', 'CAMERA', 'camstnd_to_camcrch',-1, false},
	{'crouchcome', 'CAMERA', 'camcrch_cmon', -1, false},
	{'surrender', 'ped', 'handsup',-1, false},
	{'fu', 'RIOT', 'RIOT_FUKU',-1, false},
	{'fu2', 'ped', 'fucku',-1, false},
	{'scratch', 'MISC', 'Scratchballs_01',-1, true},
	{'beg', 'SHOP', 'SHP_Rob_React',-1, false},
	{'what', 'RIOT', 'RIOT_ANGRY',-1, false},
	{'photograph', 'CAMERA', 'picstnd_take',-1, true},
	{'mourn', 'GRAVEYARD', 'mrnM_loop',-1, true},
	{'cry', 'GRAVEYARD', 'mrnF_loop',-1, true},
	{'puke', 'FOOD', 'EAT_Vomit_P',-1, false},
	{'vomit', 'FOOD', 'EAT_Vomit_P',-1, false},
	{'laugh', 'RAPPING', 'Laugh_01',-1, true},
	{'plant', 'BOMBER', 'BOM_Plant',-1, false},
	{'grab', 'CARRY', 'liftup',-1, false},
	{'putdown', 'CARRY', 'putdwn',-1, false},
	{'cpr', 'medic', 'cpr',-1, false},
	{'slapass', 'SWEET', 'sweet_ass_slap',-1, false},
	{'bitchslap', 'MISC', 'bitchslap',-1, false},
	{'shove', 'GANGS', 'shake_carSH',-1, false},
	--{'dive', 'ped', 'EV_dive',-1, false, true},
	{'roadcross', 'ped', 'roadcross',-1, true},
	{'roadcross2', 'ped', 'roadcross_female',-1, true},
    {'roadcross3', 'ped', 'roadcross_gang',-1, true},
	{'handsup', 'ped', 'handsup',-1, false},
	
	-- Customs
	--{'handsup2', 'originalRPCustomAnims', 'handsup', -1, false},
    {'leanidle', 'originalRPCustomAnims2', 'leanIDLE', -1, false},
    --{'copidle', 'originalRPCustomAnims3', 'DEALER_IDLE', -1, false},
	{'surrender', 'originalRPCustomAnims4', 'camcrch_cmon', -1, false},
	{'surrender2', 'originalRPCustomAnims5', 'cower', -1, false},
	{'surrender3', 'originalRPCustomAnims5', 'handsup', -1, false},
	{'sign', 'originalRPCustomAnims6', 'camcrch_cmon', -1, false},
	{'sign2', 'originalRPCustomAnims7', 'Coplook_loop', -1, false},
	{'sign3', 'originalRPCustomAnims8', 'RAP_A_Loop', -1, false},
	--{'sign4', 'originalRPCustomAnims9', 'RAP_A_Loop', -1, false},





} 