addEvent("weaponSkill > giveWeaponToPlayer", true)
addEventHandler("weaponSkill > giveWeaponToPlayer", resourceRoot, function(weaponID)
    takeAllWeapons(client)
    giveWeapon(client, weaponID, 99999, true)
end)

addEvent("weaponSkill > updatePlayerWeaponStat", true)
addEventHandler("weaponSkill > updatePlayerWeaponStat", resourceRoot, function(statID, newValue)
    setPedStat(client, statID, newValue)
    takeAllWeapons(client)
end)

addEvent("weaponSkill > setPlayerMoney", true)
addEventHandler("weaponSkill > setPlayerMoney", resourceRoot, function(newMoney)
    setElementData(client, "char:money", newMoney)
end)

addEvent("weaponSkill > takePlayerAllWeapon", true)
addEventHandler("weaponSkill > takePlayerAllWeapon", resourceRoot, function()
    takeAllWeapons(client)
end)